# Generated by Django 4.2.13 on 2026-08-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="이벤트 유형"),
                ),
                (
                    "recipients",
                    models.JSONField(default=list, verbose_name="수신자 이메일 목록"),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="제목")),
                ("contents", models.TextField(verbose_name="본문(HTML)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("sent", "발송 완료"),
                            ("failed", "발송 실패"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="시도 횟수"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="최대 시도 횟수"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="마지막 오류"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="발송일시"
                    ),
                ),
            ],
            options={
                "verbose_name": "알림 메일",
                "verbose_name_plural": "알림 메일",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "loginid",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="로그인 ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=150, verbose_name="이름"),
                ),
                (
                    "mail",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "deptname",
                    models.CharField(blank=True, max_length=150, verbose_name="부서명"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자",
            },
        ),
    ]
